apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tmp-po
  name: tmp-po
spec:
  containers:
  - image: nginx:latest
    name: tmp-po
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
